# Generated by Django 5.1.2 on 2024-10-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser_double_minor_customuser_minor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('locations', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('show_news', models.BooleanField(default=True)),
                ('integration_method', models.CharField(max_length=255)),
            ],
        ),
    ]
