# Generated by Django 5.1.2 on 2024-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_campaign_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(default='campaign_images/default.jpg', upload_to='campaign_images/'),
            preserve_default=False,
        ),
    ]
