# Generated by Django 5.1.2 on 2024-11-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
    ]
