# Generated by Django 5.1.2 on 2024-11-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_customuser_referral_points'),
        ('main', '0012_upcomingevents'),
    ]

    operations = [
    ]
