# Generated by Django 5.1.2 on 2024-11-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20241104_1611'),
        ('main', '0013_merge_20241104_2100'),
    ]

    operations = [
    ]
