# Generated by Django 5.1.2 on 2024-11-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_20241104_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
