# Generated by Django 5.1.2 on 2024-11-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customuser_is_first_login_alter_customuser_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_first_login',
        ),
    ]
