# Generated by Django 5.1.2 on 2024-11-20 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points_to_redeem',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('points_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
