# Generated by Django 4.2.16 on 2024-11-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_campaign_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_campaigns',
            field=models.ManyToManyField(blank=True, related_name='completed_users', to='main.campaign'),
        ),
    ]
