# Generated by Django 5.1.2 on 2024-11-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_customuser_completed_campaigns'),
        ('main', '0022_remove_campaign_completion_campaign_completed_by'),
    ]

    operations = [
    ]
