# Generated by Django 5.1.2 on 2024-12-01 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_campaign_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncompletion',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
