# Generated by Django 5.1.2 on 2024-12-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_upcomingevents_unlimited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='completed_campaigns',
            field=models.ManyToManyField(blank=True, related_name='completed_users', to='main.campaigncompletion'),
        ),
    ]
