# Generated by Django 5.1.2 on 2024-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_customuser_completed_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncompletion',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
