# Generated by Django 5.1.2 on 2024-12-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_campaign_completed_by'),
        ('main', '0029_campaigncompletion_name'),
    ]

    operations = [
    ]
